[features]
seeds = false
[programs.localnet]
mysolanaapp = "6Co28kyQJfuySddKCNjJ2Jgt4tVWSqLExZvrSoXcpudx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/adil/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
